services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: danztee
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - finguard-net
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "FALSE"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - finguard-net
    depends_on:
      - postgres
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - finguard-net
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - finguard-net
    restart: unless-stopped

#  eureka-server:
#    image: danztee/eureka-server:latest
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - finguard-net
#    depends_on:
#      - zipkin
#    restart: unless-stopped

#  api-gateway:
#    image: danztee/api-gateway:latest
#    container_name: api-gateway
#    ports:
#      - "8083:8083"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - finguard-net
#    depends_on:
#      - zipkin
#      - eureka-server
#    restart: unless-stopped

  customer-service:
    image: danztee/customer-service:latest
    container_name: customer-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - finguard-net
    depends_on:
      - postgres
      - rabbitmq
    restart: unless-stopped

  fraud-service:
    image: danztee/fraud-service:latest
    container_name: fraud-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - finguard-net
    depends_on:
      - postgres
    restart: unless-stopped

  notification-service:
    image: danztee/notification-service:latest
    container_name: notification-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - finguard-net
    depends_on:
      - rabbitmq
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  finguard-net:
    driver: bridge