server:
  port: 8761

eureka:
    client:
      fetch-registry: false
      register-with-eureka: false

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans

spring:
  application:
    name: eureka-server